### ISSUE TITLE
What's the status of this fork?

### ISSUE THREAD

**Issue by theirishpenguin** [hintmedia/rspec-jumpstart#2]
Hi @tjchambers, I just noticed your fork of rspec-kickstarter. As the last commit to seratch/rspec-kickstarter was back in Jan 2016, would it be correct to say that it is better to use your fork now?

In particular, I'm interested in seeing this issue in the seratch/rspec-kickstarter repo resolved https://github.com/seratch/rspec-kickstarter/issues/7. I was thinking of tackling it myself - has it been something you've looked at?

**Comment by tjchambers** [comment]
I am actively using this fork myself. It shares some of the original mode of discovery, but a much different mode of spec creation (more complete IMHO). 

I have not looked at that issue, and it is not something I need, but would welcome any contribution.

**Comment by tjchambers** [comment]
BTW I am using this on a number of other projects where test coverage is spotty, so am making adjustments/enhancements to make it more widely useful.

**Comment by dinjas** [comment]
This gem has been published to Rubygems.org as `rspec-jumpstart`.
