### ISSUE TITLE
Releasing this fork?

### ISSUE THREAD

**Issue by Ch4s3** [hintmedia/rspec-jumpstart#6]
@tjchambers do you have any plans to release this fork as a published ruby gem?

**Comment by tjchambers** [comment]
WHile I don't have any problem with that, I don't want it to conflict with original.

**Comment by tjchambers** [comment]
This is actively being "maintained" but it is different than the original.

**Comment by Ch4s3** [comment]
would it make sense to give ti a new name?

**Comment by arturtr** [comment]
+1 for release

**Comment by tjchambers** [comment]
Naming suggestions? Am open.

**Comment by Ch4s3** [comment]
hum... spec-starter

**Comment by tjchambers** [comment]
I kinda like that.

**Comment by Ch4s3** [comment]
It could be worse.

**Comment by arturtr** [comment]
`rspec-init`, `rspec-blank`, `rspec-mould`

**Comment by arturtr** [comment]
`rspec-kickstarter2` ) 
`rspec-starter`

**Comment by dinjas** [comment]
I like all the suggestions. A few more:

`rspec-bootstrap`
`rspec-jumpstarter`
`rspec-assist`/`rspec-assistant`

**Comment by tjchambers** [comment]
I choose rspec-jumpstart. It does not confuse with bootstrap, and is explicit.

So rspec-jumpstart it is.

**Comment by dinjas** [comment]
Released to Rubygems as `rspec-jumpstart`! Thanks everyone
